# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Viper-Simple-DemoApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Viper-Simple-DemoApp

  pod 'PKHUD'
  pod 'Alamofire', '4.9'
  pod 'AlamofireObjectMapper'
  pod 'ObjectMapper'
  pod 'Kingfisher'

end
